### ISSUE TITLE
Python 2.7 and Windows does not support os.link

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-backend-client#19]
It seems `os.link` does not work on Windows with Python 2.7...

Herer is the ouput I have:

```python
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\user\appdata\local\temp\2\pip-build-4prmlc\alignak-backend-client\setup.py", line 6, in <module>
        del os.link
    AttributeError: link
```

If you can reproduce issue ?

Otherwise, maybe make a conditionnal statement for this line in `setup.py`:

https://github.com/Alignak-monitoring-contrib/alignak-backend-client/blob/develop/setup.py#L6

If I remove this line, install succeed.

**Comment by mohierf** [comment]
See https://bugs.python.org/issue8876 for history. Fixed with #20
